== 港女家姐自白 

趁住屋企無人，又成幾個月無俾人扑過。我又忍不住做埋啲變態嘢。除褲淨係着住件畢業袍，入面真空全裸咁係屋到行嚟行去，又行出露台企，專登比風刮起件袍，好似想分享我自豪嘅A4 腰比街坊睇。之後就係大廳對住塊鏡擺性感post, 係袍邊露下我個32C波邊, 又扒係地下用個patpat係咁對住塊鏡自己係到搖，搖到件袍瀡晒落嚟show咗我個大屁股出嚟。少晒太陽所以都幾白幾滑，屁罅中間可以清楚見到自己個西，因為好少機會睇到所以不其然伸手用手指撥開佢睇下佢入面，一摸先知自己已經係咁出水下面濕晒，成手都係白色漿，望住塊鏡睇得唔係好清楚，就好似狗仔痾尿咁抬起一隻腳，雖然前排係咁發姣幾乎晚晚做愛，有時仲一晚幾次，見到仲係好粉紅色，都放心咗啲。當我忍唔住塞咗我手指入去玩咗幾下準備自慰之際。屋企大門突然打開咗，我媽媽爸爸同兩個細佬入咗嚟全部發呆咁望住我。我媽媽就好嬲咁話我做乜成日都係咁，上次已經搞到成家雞犬不寧點解仲唔夠，仲話寧願我出去做雞比人玩都唔好攪到屋企人，係咁鬧我賤格連畜牲都不如。我嗰刻無講嘢，淨係企番起身用件袍遮住自己就走番入房喊。但仲聽到我爸爸安慰緊我喊緊嘅媽媽。我喊到攰就不經不覺瞓咗。聽到出面碗碟聲先知就嚟食飯。一家人幾醜始終都要見面，我唔敢再Tshirt底褲出去，唯有着到密密實實好似出街食飯咁出房。一出到去見我爸爸係到睇電視無望我，細細佬就低頭唔咁望繼續打機。大細佬本來就好開心咁想叫我，但係我媽媽瞪咗一眼佢就無出聲。淨係同我打咗個眼色就繼續撳電話。我呀媽就突然同我講，話知我唔舒服所以準備咗一份比我番房食。我聽完又忍不住眼淚就細細聲講咗句唔該就番咗房。之後都係呀媽攞咗入嚟。我一路食，佢一路望住我。本以為佢會開聲鬧我。但佢粒聲都無出，淨係望住我。突然佢用手摸我個頭同掃我啲長頭髮。掃到第二下時我就忍不住大聲喊咗出嚟。攬住佢係咁講對唔住。佢繼續掃我背。話我大個咗好多嘢都無所謂。但係佢仲要照顧兩個細佬所以都希望我諒解。安慰我話我似我爸爸咁靚。咁多人追。要我應承佢唔好再係屋企攪。我話咗以後唔會之後再比佢抱多陣佢就執番啲碗碟走番出廳自己一個人食飯。

其實下個月我就大學畢業，本應係好開心嘅事情。但係因為一件事比爸媽發現咗。整到而家成日面阻阻。同枱食飯個個都尷尬唔出聲無嘢講。同細佬攬頭攬頸親蜜啲都比人望到實。畢業禮我都唔知點算。經過今日我希望可以有所改善。成件事要由頭講起。

我同屋企人不嬲都感情好好，特別同我大細佬特別friend, 可能因為年紀唔係差好遠但細細個我已經要開始照顧佢。所以成日攬住拖住手周圍去。大個咗就成日一齊行街睇戲買衫。係一對感情好好嘅姊弟。到細細佬出埋世就兩兄弟玩得埋咗。同我反為疏遠咗。但正好因為我都大個無同佢地玩啲低能嘢。

後來我拍咗拖，係隔離學校嘅學生大我幾年，我第一次就係比咗佢。雖然係好痛，但係做多幾次就越來越舒服。後來我反而日日都想要。但係無錢無地方，只可以偷偷地等屋企無人，或者樓梯公厠公園咁。細細個我就係好多地方玩過。呢啲都係環境迫出嚟。到咗後來嗰男仔有咗第二個就同我分手。我傷心都日喊夜喊。嗰時我大細佬都大個。識得嚟安慰我比我攬住係咁喊又陪我週維食同玩散心。感情又開始好番。之後因為要應付考試就無心機拍拖。到入咗大學之後雖然有人追。拍個幾次散拖就好快無咗。唔知係咪細個時比人開苞同打野戰太激。拍幾次拖同佢地做愛都太正常好似滿足唔到我。

無幾耐大細佬識咗個女仔仲帶番嚟屋企，個女仔長直髮面圓圓細眼但係帶住個好厚眼鏡。着得老老土土成個文學少女咁但就好有禮貌。我同媽媽都好中意佢，我就好似多咗個妹咁。感情都好好乜都講。直到有一日佢突然text我話問我啲關於我大細佬嘅嘢。我話無所謂。點知佢就問我細佬下面大唔大。因為佢話大細佬約佢上屋企話聽日無人。佢諗住應該會會比我細佬扑但又驚會痛。所以問下我有啲心理準備。我心諗我點會知。就算細個一齊沖涼嗰時都咁細個。條嘢細到睇唔到咁滯。我唯有安慰佢話唔洗驚其實一啲都唔痛。佢又問咗好多點服侍男人嘅方法。我都一一講比佢知。佢好多謝我。到咗夜晚食完飯。不出所料到我細佬鬼鬼祟崇咁入咗我房。原來係聽日諗住同佢女友扑嘢所以嚟請教我。我就送佛送到西咁將以前男友對付我嘅方法教晒佢。佢仲問到好仔細問到我不其然下面濕晒。問咗成個鐘佢先走我嗰時已經成條底褲濕晒。佢一出房我就忍不住狂捽自己個陰核。之後再伸手指入去大脾用力狂夾。好快咁我下面就震咗幾下高潮咗。之後無着褲躺係床上面。厊開大脾將個西對住窗口。比啲風吹入個西窿入面就瞓着咗。

第二日我出街仲特登晏啲先番屋企，比夠時間佢地兩個慢慢玩。番到屋企時見到廳無人以為間屋得我一個，之後先聽到我間房閂咗門入面有聲。仔細聽下原來我細佬同佢女友係入面啱啱先開始玩。我心諗唔係吖嘛，係我房到做。但係聽到有啲呻吟聲就坐係房門偷聽。聽到啲啜啜聲。我細佬跟住我教咁一邊啜佢女友對波，一邊讚佢又白又大又軟熟。話佢粒lin 好甜好好食。好似食緊士多啤梨咁。之後聽到佢女友叫佢唔好用嘴唇夾住佢咪lin嚟拉。拉到佢長晒又腫痛仲要係咁搖。我細佬好似無理佢仲大力啲咁我聽到佢女友慘叫。之後又叫佢將大脾厊大啲比佢手指易郁啲。我就係咁聽到條女係到呻吟叫唔好，又叫大力啲。到聽到啲水聲我知我細佬學我教佢咁高速用手指玩佢女友嗰西玩到出晒水。我心諗條女都幾似我。嗰時先發覺我隻手已經伸咗入褲入面揉緊陰核同另一隻手搓緊自已個胸。我索性跪係地下挨住房門一邊自慰一邊聽。

條囡係房入面比我細佬玩到出晒水同呻吟。之後就係咁叫話要。我以為我細佬忍唔住要屌佢時。條女突然叫話做乜。聽到我細佬話要食西。之後就淨係聽到條囡啲淫叫聲。叫到我都好high係咁了自己個西。成手成底褲都係水仲一大陣西水味。都唔知係我自己定係房入面飄出嚟條囡啲西味。房入面好似有啲動作轉咗身之後就兩個都無出聲。我有啲心急想打開門睇下。突然又聽到啲聲。我細佬叫佢條女扒係我床上面抬高屁股。佢就由後面入。我心諗第一次就比人咁直接屌到咁入。一定痛死條囡。不出所料條囡話好痛叫我細路慢啲。我細佬可能心急要入去，唔聽夾硬塞入去。係咁話好窄入唔倒。但條囡就一直話痛。最後條囡呀咗一聲。入面又無晒動靜。隔咗一陣我細佬問好啲可以郁未。條囡就叫佢慢慢同唔好郁太多。之後就聽到佢噢噢聲咁比人屌緊。我嗰刻就係咁用力捽自己個西因為就嚟高潮。而房入面都好似加快咗速度同啲啪啪聲越來越大聲。我差不多高潮時突然聽到大門有聲。就立即企起身。再伸手入口吮番晒自己手上面啲西汁。扮無嘢咁講嚟啦開門。聽到房入面突然好混亂。我開大門見到媽媽。佢仲問係咪好熱做乜成頭大汗成面紅晒。頭髮又亂晒問做乜事。我大聲咁話無嘢。之後我細佬同佢女友就由我房行番出嚟叫媽媽咁之後先無事過到骨。嗰晚佢女友同我地一齊食埋飯仲幫手洗埋碗先走。氹到我媽媽好開心。

食完飯我已經頂唔住即刻攞衫入廁所沖涼。頭先搞到半天吊仲要成西污糟邋遢啲毛黐住條底褲。入到去即刻除晒衫褲坐咗係廁盤。一隻腳舉高放係洗手盤，一隻就垂落地下。厊大對腳個西對住廁所門開始了自己個西。一時就摸下塊西出面啲陰毛，一時又了啲西水出嚟漿住啲毛。一時又用手指吖大佢嚟又開又合。又將手指一隻隻咁塞入去。塞到漲住痛忍不住伸脷連腳都伸都直晒就抽筋咁。入到三隻之後再又開又合咁撐開個西。再幻想而家有人開門見到我咁，衝入嚟就將佢條大肉棍一下用力插入我個西到屌死我為止。

當我就到高潮時我細細佬突然叩門問我得未。佢肚痛要入嚟。我即係叫佢唔好住。我起身沖身。沖完先見到個坐廁上面同地下地氈全部係我啲白色西汁。我發晒茅咁用花洒求其沖下就出去。仲要比我細細佬怨話我耐。一入到廁所仲要大叫。嚇到我以為佢見到我啲西水先聽到佢話我整到地下濕晒。我無理佢即刻入房淨係諗住要繼續要高潮。

唔知行乜衰運，嗰晚我由十點自己搞到兩點幾。捽到自己個西無晒感覺。揸到個波手印都出埋。玩到個窿都痛但係就越心急就越無高潮。成晚就係到唔上唔落。試過用原子筆香水唇膏插入去都唔得。就算係用hair spray 咁大支咁粗屌入去我都高潮唔到。糊意亂想咁滿腦子都性。摸摸下床摸到條唔係我嘅T back.. 先知我細佬條囡頭先裙裏面乜都無着行嚟行去，我再見到床邊床單上面有啲漬。我用塊面挨埋去係咁聞。聞住第二個女人啲西水味我仲發情得緊要。淨係諗住我細佬用佢條大肉棍屌佢條女。我係傍邊睇住。我終於忍唔住出咗房。全屋都瞓晒無晒燈。我經過我細佬間房佢地無閂門。我走咗入去。兩個細佬住一間房瞓碌架床。大細佬瞓上面。兩個都瞓到好稔。但係突然我見到大細佬下半身張被郁郁下就停咗。。我好似知道佢做緊乜咁。可能係今朝屌完條女而家回味緊自慰。我就企係樘梯上面。上半身鑽咗入佢將被入面。隱約見到佢隻手揸住佢自已條嘢。我已經忍唔住一咀含落去係咁啜。佢之前應該射咗幾次成條底褲都又濕又凍咁黐住我塊西。我一邊含一邊聞住佢啲精臭腥味。另一邊就用隻手指挖自己個西。都唔理我淨係着住條底褲企住梯級到。下面細細佬如果醒咗就乜都睇到晒。

大細佬比我含住但佢就無反應繼續好似瞓咗咁。佢條嘢係我口入面越啜越大。我就係咁用脷打圈同有時就啜佢春袋同用手幫佢打飛機。玩咗一陣我就企係度高潮咗。我仲感覺到我下面好似對住我細細佬噴咗啲水出嚟。我覺得自己真係好淫。繼續食我大細佬條嘢。佢真係硬得好緊要。到我捽到自己第二次高潮時佢又射咗係我口入面。我直程顛到唔肯放口繼續用脷舐佢龜頭。舐到佢成個人縮晒仲叫。我就兩隻手一前一後插入我兩個窿企係到自慰。到佢再射時我己經唔知高潮咗幾多次。我腳震震咁落番樓梯。見到下面張床比我噴到濕晒。我已經攰到無理希望佢第二朝自己會乾。之後就番咗房瞓。

瞓到半夜半夢半醒之際。覺得好似有人入咗嚟鑽咗入我被入面開始舔我妹妹。仲越來越大膽用手指插入去了。我嗰下驚到唔敢郁。想大聲叫但又驚佢係我細佬。如果比人知道爆我先去幫佢含我都好醜。唯有由得佢幫我舔。佢食咗好耐食到我本來已經玩到無感覺嘅西而家又腫又漲痛。嗰種感覺又難受又有啲絲絲快感好難表達。食到後來啲水聲越來越大。而佢對手越來越唔禮貌越摸越上。開始搓我個胸。我三個敏感位比人咁玩法玩到我不其然係咁扭腰。可能玩到佢都頂唔順佢就用被蓋住我個頭。壓咗我身上面用佢jer jer插入我身體入面。我好耐無比人屌過幾乎唔記得咗比肉棍插入去原來係咁滿足充實。佢一邊好快咁郁佢條腰抽插得我好快。到後來我直程攬住咗佢對腳繞住佢幫佢䟴。佢最後加快咗速度大大力咁撞咗我西幾下。我感覺到佢係我入面係咁震同我肚入面好熱好熱。我知道我比佢中出咗。佢射咗好多好耐都唔捨得出番嚟。仲不停咁玩我對波同啜我乳頭。最後佢好唔捨得咁屌咗我幾十下先靜靜雞起身開門番房。我驚咗一陣都唔敢起身。但係忍不住自己摸下面。真係比人射咗好多入去而家湧緊出嚟。我用手接住咗一啲攞出嚟玩。手指一開一合咁整咗好多絲絲出嚟。望咗一陣都係放咗入口試味。食完又伸手落去抹多啲出嚟啜。等咗一排先夠膽行出房睇下點。天已經微光。全家人都好似無事發生咁瞓到好稔。

到咗第二朝起身。個個都無嘢正正常常咁。整到我懷疑自己係咪發花顛發夢。但我番房望下床單同我條底褲。上面仲有一大灘漬係上面証明我真係比人攪過。比個唔知係邊個熟人姦嗰種感覺真係好剌激。番學上堂時一諗起就夾實對腳。落堂趕住去廁所驚我啲西水流到條褲後面濕晒比人睇到。

到咗夜晚我突登早番房上床等。等等下就忍不住自慰。係咁幻想比人狂插。玩到半夜啲人瞓晒覺都無動靜就瞓咗。醒番又開始自慰。成晚攰咗就瞓。醒咗就玩自己。玩到成間房都係西水味。天光都無人入嚟先瞓一陣出門口。就係咁連續幾晚我等人屌但無人嚟。有一次我直情急到高潮時抬到條腰高一高咁。見住自己啲西水向天光板噴出嚟。但係都係無人入嚟再屌我。晚晚無覺好瞓淨係自慰又食唔飽。朝朝起身番學好似喪屍咁滿腦子想揾人插我。

星期五晚一家人食完飯我就立即番房坐係床到扮睇書。其實我着得件大T shirt下半身乜都無淨係比張被蓋住。開始就一路睇書一路用手指了西自慰。到後來就開始揾嘢插入去。插住咁坐係床睇書，到最後我一支唔夠直程用咗兩支一前一後咁插住自己。一直咁玩等屋企人瞓晒。到咗十二點幾我呀媽突然開門，叫我早啲瞓唔好咁夜。我嚇咗一跳求其咁應佢之餘，我個西收緊到迫咗條電動假九出嚟。好彩我無開到唔係就係被入面係咁彈就穿煲。我呀媽走咗之後我就更加心急。我熄咗燈等到一點半鐘聽到出面啲鼻寒聲估到佢地瞓晒。我下面已經濕到一榻糊塗。成大髀都係西水，用手一摸已經全手都係。我仲係咁聞自己手上面啲西水仲用脷舔下試味。覺得自己真係好變態。

我就偷偷地打開房門彎住腰行咗出去。嗰時我淨係着住件T.. 同我屁股比支hair spray 插住企唔直。 我靜靜雞咁入咗細路房企咗上樘梯上面捐咗入大細佬張被入面。下半身就凌空掛住係到。用一隻腳企係梯到借力。我細細力咁拉低咗大細佬條底褲。見到佢軟綿綿嘅肉腸。個龜頭仲比包皮包到實。同聞一陣尿騷味我即刻頭皮發麻。好似個腦入面溶咗咁。我輕輕咁捋開咗佢包皮。見到上面有好多白色漬係上面。諗起可能條嘢啱啱先比第二條女含完我就更加興奮。忍不住一啖含住。立即食到咸味同一陣好剌激嘅氣味衝入我鼻腔。我津津有味咁食住啲又咸又腥嘅汁。一邊用脷舔佢龜頭將佢滑滑好似精液嘅分泌啜埋嚟食。食到佢硬晒就開始食佢春袋。食到佢下面濕晒就索性要佢抬起腳食佢屎眼。雖然大細佬無出聲但我知佢應該係醒咗享受緊。我啜到佢屁眼濕晒之後仲用脷鑽咗入去。感覺到我會一下用力佢就收縮夾入我條脷之外。佢jer jer仲會用力跳一下。我覺得實在太好玩就不斷用力鑽佢都加快咁彈下彈下。打到落我塊面到好鬼死硬。當我食夠佢屎眼想再食佢啫啫等口爆時。大細佬忽然擰轉咗身打側對住我瞓。雙手捉咗我個頭就開始抽插我個咀。屌到我吞唔切啲口水流到床單上面都係。開始時我都好享受下。佢個龜頭係咁係我口到出出入入。我就用咀唇包到佢實一實嚟啜好似食雪條咁。我再貪得意整濕手指輕輕咁插入佢屁股到。我一插佢就用力向前頂入啲。因為其實係岳高咗頭比佢屌緊個口，佢越插越入時開始就屌到我脷嗰到。之後越玩越滑同越順就下下頂到我喉嚨。到我手指加速同幾乎成仲隻手指插晒入佢屁股後。佢直情跟住我節奏向前頂。仲要用力按住我個頭扭腰用我個咀嚟磨佢龜頭。開始我仲可以放鬆。到佢頂得太入時我自然就收緊我個咀佢反而緊加舒服同插得更大加。最後我頂唔到比佢一下就插咗入我喉嚨裏面。好似骾骨咁比人吖大我喉嚨唔上唔落。雖然我之前有男朋友同人口交過。但比人屌到咁入係第一次，口水眼淚都出晒淨係可以唔唔聲。

因為太緊張關係我唔小心pat pat用力就迫咗個插住我個hair spray 樽出嚟。我越想用力夾住佢唔比佢跌出嚟反為就越迫得佢出。到最後就夾唔住要跌出嚟。我心諗實整醒爸媽見到我唔着褲含住我細佬條啫啫。個頭又比人撳實點掙扎都無用。唔知點算好之際突然feel 到個樽又插番入去。仲要開始一出一入咁抽插我屁眼。之後有隻手扶住我一邊大髀打到好開。我陰核就比個好軟好暖嘅咀唇包住到啜。仲比人用手指伸入我個西到係咁挖同磨我g 點。我突然背脊發軟同衝到我後腦。比我兩個細佬一前一後咁三點攻擊我覺得自己真係好淫賤。我一邊享受呢啲天堂般嘅快感。一邊雙搓自己對波。當我下面比人按到頂唔順高潮噴尿之際。我大細佬都向住我喉嚨射精。我比佢啲精嗆親係咁咳佢都唔理撳住我個頭係咁繼續射。我就咳到吸咗啲精入鼻上腦咁。就鼻哥窿噴入出嚟。淨係聞到啲精臭腥味。嗰時我知我下面不斷向住我細細佬噴水，開始時我估佢縮開咗但後來我一邊噴佢一邊舔我個西幫我食晒佢。

就係咁我個西比人啜緊時。我大細佬已經抖晒大氣條嘢軟晒咁係我個口到。我慢慢一路用力吸佢留係入面啲精一路抽番佢出嚟。估唔到仲有咁多流到出嚟。好似食豬骨咁妳好玩。到抽晒出嚟時我大細佬仲將我面上面啲精（或者係鼻涕）抹番晒入我個口到。我就用手指抽佢屁股多幾下就擒番去下格床。見到我細細佬好乖咁跟住我佢又扒低食我個西。一刻都唔肯鬆口離開我下面嗰咀。見到佢咁我都有啲感動同母愛泛濫。就拉佢坐起身嚟錫。佢成頭成面都比我噴到濕晒。我就一路錫一路舔。再一路用手玩佢已經硬到紅晒嘅啫啫。我一路由佢塊面舔到佢心口。再啜佢兩粒乳頭。啜到佢扭身扭勢我就推低佢瞓咗係床到錫佢肚臍再一啖咬住佢包皮，再用咀唇幫佢退開就成條啜晒入口。再順便轉身騎住佢塊面要佢一齊食西。佢好聽話咁好努力咁幫我舔。我都好仔細咁研究佢下面。雖然無大細佬咁長。但係就粗過佢好多。又硬又大味。我啜住佢流出嚟嘅汁好開心。

當我好留心咁品嘗緊我細細佬條啫，同一心諗住今晚破紀錄一晚食晒我兩個細佬嘅精。我細細佬就一邊用脷鑽入我西窿入面了，一邊就揸住個樽頂入去，差不多成支頂晒入去頂到上我肚臍咁滯。突然聽到我大細佬擒落嚟。坐咗係我背脊壓住我兩條肉蟲，拉高我件T 就揸我對波。有時仲捉住我嗰頭嚟搖。當我好似飛機杯咁比細細佬抽插。玩到咁上下佢就移咗落去用佢啫啫磨我個西。我以為佢硬咗就會插入去。點知佢就塞咗入細細佬個口到要幫佢口交。睇住兩個男人搞基真係好肉緊。 我一邊幫手撳住我細細佬用我屁股坐住佢。等佢比人屌個口屌到好入時，見佢條腰係咁向上頂掙扎時我就深喉吞佢條啫啫。我大細佬見到咁就用手按住我嗰頭再攞咗我屁股個樽出嚟。由我屁眼開始先插一下，之後就插我個西，再屌細細佬個咀，三個窿輪流入。玩到我好興奮。我細細佬就好肉緊咁大力揸我對波。最後好似點指兵兵咁。竟然用細細佬口爆咗。我嗰下覺得有啲可惜。其實我想比佢中出。但係見到我細細佬咁慘，就轉左身抱住佢嚟錫，同佢濕吻食番晒啲精之餘再一屁股坐咗係佢啫啫到搖。坐到咁上下細細佬忍不住就推低咗我撳住我係麻開始瘋狂抽插。大細佬見到就坐咗係我身上面用我個波夾住佢條啫玩乳交。佢已經又硬番我就順便用口再佢啜。同一時間比佢兩個屌我兩個咀。擦到我心口同個西入面好似火燒咁。最後我細細佬抵擋唔住我西西嘅夾攻。將佢啲子孫射晒入我肚入面而大細佬都頂唔順射咗上我心口。仲用嚟抹我個波同乳頭。玩完兩個都攰就比我一邊一個抱住瞓。我咁大個女第一次左擁右抱好自豪。而佢兩個就好唔客氣。一人扯住我一邊波係咁啜。就算上面全部係精都唔理。我對波比人左右扯開好似比份屍咁。我對手又比佢地個頭壓住。只係夠長去摸佢地春袋同了佢地屁眼。佢地就將我對腳舉起拉開。兩隻手十隻手指爭住玩我個西窿。玩到硬番時就輪流一人幾下咁用啫啫屌我。

最後都係細細佬心急忍唔住就一個人好自私咁壓住我嚟屌，開頭我一邊比佢屌一邊幫大細佬口交。後來佢直情舉高我對腳用佢身壓住大大力咁撞我個西。我成個人直情比佢壓到對摺咁滯。大細佬無得屌我個咀，就行咗去後面。見到夠位就一下插咗入我屁股入面。我第一次比人前後咁入。原來當屁股塞咗支咁大嘅嘢係到抽插時。係全同前面嗰條用唔同方向力度拉扯我陰道好似要將佢攪爛咁。真係好high.. 插咗唔知幾耐我腦裏面一片混亂淨係覺得我個西同埋屁股全比佢兩個插穿變得一個大窿。大細佬突然抽咗出嚟我覺得屁股比風吹咗入去好涼。個死仔竟然迫佢啫啫入嚟，已經比細細佬插到實一實嘅西入面。我想叫唔好時比人掩住咗個咀。之後就開始感覺到由西窿口一吋一吋咁比人撑開到插到最入時我已經漲到高潮咗覺得佢地嗰兩條嘢不斷咁係我西到變大就嚟整爆我個肚。

佢地可能feel 到我陰道一下一下咁收縮知道我高潮咗。一啲都無諗住放過我仲要狂郁。因為太多人所以佢地就瘋狂咁亂插。我第一次感覺到兩支棍由唔到方向插我個西。我個西好似比佢兩個屌到變晒型。屌到咁上下大細佬就抽番出嚟淨得番細細佬專心咁繼續努力咁搞我。大細佬向我打咗個眼色我就知佢想點。我就好温柔咁攬住我細細佬，仲用雙腳纏住佢條腰夾實佢。我大細佬就係佢用力頂住我嗰下一下就屌咗入細細佬屁股入面。我即刻feel到我肚裏面好滑同有啲熱。就知道細細佬射咗。但係佢一啲都無軟到。大細佬仲扶住佢個屁股兩兄弟夾啱節奏一齊屌我。每幾下我就感覺到多啲精係我肚入面。嗰下不斷比人中出嘅感覺真係好淫。直情滿到佢地每屌一下就有嘢係我西到流出嚟整到我屁眼又濕又痕。到最後大細佬就行番去我前面，要我學狗咁扒係到。佢兩兄弟就一前一後咁夾攻我。玩得一陣就要我轉身換窿插。咁樣轉幾次身之後我大細佬就成個抱起咗我。而細細佬就企係我後面扶住。兩個一齊抱起我凌空一齊屌入我個西入面。我肉緊到係咁用手抓住大細路嗰背。仲好大力咁啜佢條頸，佢兩個就下下抬高我之後由我路落去比佢兩條啫頂住。仲用手指挖我屎眼同大力由後面揸我個波。最後我比佢地玩到高潮同噴水。啲水沿住佢地春袋同大髀流落地氈。佢地亦無浪費我呢個淫家姐，一齊射晒入我入面。

射完之後我地三個攬住一齊坐係床休息一陣。因為我仲比佢個夾住係中間所以啲精就流晒落佢地條啫同春袋上面。我就撳住我西窿企番起身唔比啲精流出嚟。之後就每人送多次事後簫食番乾淨佢地下面。佢地再抱住我一人一邊咁啜住我個波瞓咗我先撳住個西窿無着衫咁入咗房。

番到房靜落嚟我先感覺到我對波又腫又痛，特別係乳頭係咁比佢地拉扯吸啜。而家比風吹到都痛。屁股就唔洗講好似比火燒咁坐都坐唔到。我用鏡照下下面。個西同屁眼都變晒鮮紅色好似出血咁,。個屁股就有啲肉反咗出嚟夾住咗。我慢慢用手指理番順佢塞番入去。個西就比佢地插到鬆晒，而家唔似以前咁個陰唇包到緊晒，會有個西窿係中間大小陰唇就鬆弛晒咁係側邊吊住。仲要唔停咁流白色嘅嘢出嚟。我忍唔住又挖出嚟放入咀試下係乜味。結果係有兩細佬嘅精味同埋我自己嘅西水味。我真係發晒姣再自摸咗一陣先瞓。雖然擔心以後都係咁但攰得淨希望聽朝無事

到瞓醒已經係十一點幾就食晏。一睇電話就見到大細佬send咗一堆相比我。佢地兩個趁今朝我瞓到死咗咁係咁幫我影性感裸照。有啲就好肉酸淨係影我個西嘅大特寫。有啲都幾有美感。有兩張個死仔打開我西個屁眼影我肚入面我居然完全唔知。再睇落去就越嚟越過份咁用唔同嘢插我。當我個西係垃圾桶咁玩。睇到有啲嬲想出去打佢地。佢地仲要大膽到明知爸媽係廳出面，揾啫啫塞入我口到比我含同同我做愛，好彩佢地兩個一齊嚟我個口比佢地條嘢封住，唔係我瞓覺時比佢地屌到高潮呻吟佢地就週身蟻。最後佢地當然要一齊中出我所以又比佢地一齊咁插入我個西窿入面。見到佢地一左一右咁插入去張我個西扯到闊晒，諗起噚晚佢地一前一後咁插今日就左右咁嚟。我驚我下面就咁變咗闊西以後普通人餵我唔飽。我即刻睇下我下面見反為好似比噚晚好啲先放心少少。一定要去話佢地。到最尾佢地仲錄咗段video, 我本來仲以為係乜野賤格片影住我個西狂漏精出嚟。仲驚有聲所以較咗靜聲。但係播片時淨係見到佢兩個口嗡嗡唔知講乜。用聽筒聽先知原來佢地驚噚晚玩得太過份驚我有事同我講對唔住。仲話因為我太正忍唔住所以先咁。唔知點解我聽十完啖氣已經消咗一大半。到換衫時先發我噚晚着住件T細佬幫我攞番嚟。但係成件衫都係漬仲好大味。我唯有收埋等沖涼先自己洗。貪玩之下就着住佢女友條T back。發覺好鬆下先知佢女友個蘿大過我。條T back中間條布跟本貼唔緊我下面。我着住條波褲就好似無着底咁。中間個西係咁直接磨住咁行。。出到去媽媽已經急不及待咁話大細佬頸到比女友整咗個咖哩雞。我一睇先知其實係我整嘅。笑咗一兩句就比佢瞪咗我一眼再語帶雙關咁叫我小心啲。遲啲我就知死。 我心諗本小姐噚晚一個打兩個都無事。放馬過來。媽媽聽到我把聲沙晒仲好關心咁問我有無事提我食葯。我心諗喉嚨就比人屌到咁。其實要食事後丸就真。

晏晝等我爸媽出咗街之後，我就係咁問我細佬噚晚正唔正，我同佢條囡比係咪我大波好啪啲。佢開頭有啲怕羞，問問下就話佢條囡就窄啲緊啲。但係我就乜都玩得好玩好多。講講下佢就忍不住係大廳就拉低咗我條波褲捉住我由後面入。佢見到我係着住佢女友條T back。就更加發狂咁打我屁股。同索性除咗佢塞入我口到。我細細佬本來打緊機都擰過嚟望到實，我地就行過去好似噚晚咁。我係中間比佢兩個一前一後咁夾攻。大細佬因為驚條T back留咗係廳驚爸媽發現仲由我口抽番出嚟塞入我屁股夾住。玩到後來就一個係梳化打機時。我就同另一個做愛，打完就換人接力。成個晏晝我就咁由十二點做到成七點我爸媽就番先停。簡直係性愛馬拉松。我個個窿都比佢兩兄弟射幾次。去沖涼時腳軟要浸浴缸見到啲精係咁飄上水面。我仲發姣咁對住啲精講問佢地想叫我呀媽定姑媽。我諗番都覺得自己白癡。

之後我地三姐弟就越來越大膽，有時就算爸媽係屋企佢地都會偷偷拉我埋一邊淨係插我幾下。一日我隨時比佢地咁樣玩十幾二十次。為咗就佢地兩隻發情狗公我而家係屋企多數都着裙。最煩就係如果射咗入去一陣味。又唔敢成日去沖涼。我就好似個人型精罐咁行嚟行去驚人聞到。夜晚就有時偷偷入我間房做。做完一個就另外一個接住。以為做完點知第一個又硬咗番嚟再做。放假前後就成晚係我房出出入入。有時忍不住就兩個一齊嚟。我好似做咗佢地慰安婦咁。有時就我沖涼就入嚟一路沖一路做。有時出街同爸媽飲茶時。我去廁所就一定有個同我前後腳去。拉我去殘廁就扑我幾下或者要我幫佢含。有次玩完出嚟我咀角仲有條陰毛黐住。好彩我大細佬見到快手幫我攞開無比爸媽發現。我媽媽仲讚我地感好。有時去睇戲我坐中間。佢地就一人一邊用手伸入我裙底玩我個西。我又輪流扒係佢地大髀食啫。去k 就更加放膽，合唱歌時一個唱男聲，我女聲就坐係另一個大髀到俾佢屌住嚟唱。最剌激有次有侍應入嚟收嘢。我就嚇到大力坐咗係我細細佬到整到佢射精。個侍應一邊收嘢望住我問我啲嘢要唔要，我就一邊比人中出一邊話唔要。肚入面比支棍震下震下咁攪。我大細佬女友仲同我講我細佬技術越來越好，特別口交時好正，我心諗梗係，我晚晚係到幫你特訓你條仔。幾時要多謝我。跟住就幻想佢會唔會用玩我嘅方法嚟玩佢。下面又濕咗。

我地三姊弟嘅淫亂關係就咁樣維持咗大半年，其間都有啲驚險嘢例如我m 嚟遲咗。我兩個細佬都好擔心。傻傻地話會負責。雖然知道佢地無鬼用，但係都好感動下。起碼好過我之前個男友。一聽到我講笑話有咗就面都青埋想揾方法落咗去。有幾次夜晚幾乎比爸媽撞見佢地入我房，最後就扮起身去廁所。比鄰居聽到我地屋企成日有女人呻吟（其實係我嚟）。我細佬就食咗隻死貓話屋企無人時佢睇咸片啲聲，又有次我地三個急得滯爸媽又係屋企，忍不住就三個出咗門口外面做。我拉高條裙比佢兩個抱著插我西同屁眼。插到就高潮時突然有lift聲，嚇到一齊抱住我好似玩雜技咁入咗後樓梯繼續插，雖然係一前一後，但最後都係無人肯輸蝕。兩隻啫啫一齊迫入我西窿到一齊射。佢兩個射完就拉番褲鍊入屋，我就係後樓梯整咗成個字先搞掂佢地啲精。我媽媽就發覺啲厠紙m巾用得好快問我係有乜事， 我就話嗰排考試所以緊張啫。其實佢嗰兩位公子好似狗公咁捉住我日出夜出，啲精又杰。次次射完都撈唔埋一灘灘咁存咗係我肚入面。用日頭插入式m巾發覺完全吸唔到啲精入去。次次就塞住成日到夜晚攞出嚟時好似開香檳咁係咁瀉出嚟。有時佢地兩兄弟都唔識呢啲嘢。一扯開條褲就插入去都唔理我有條m 巾塞住。比佢地插到鬼死咁入好鬼難先攞到出嚟。有時求佢地幫手仲要抽水扑多幾鑊。而家就算日頭都要用夜用裝先得。我一個女人等三個窿要照顧四個細佬都算錫到佢地燶。我試過叫佢地用套做。但係一來我地做咁多次做完啲套唔知點算。我大細佬仲嚇我話塞入我西入面先到有機會先掉。我鬧到佢話當我係乜。咁樣同唔用有乜分別。啲精咪又入番我到。我係咁鬧佢白癡低能。另外就係用套真係無咁舒服。最後大細佬唔知邊到揾到話如果啲人dna 好似就會好難大肚。話我地啲dna一定似到十足話唔會咁容易有。佢仲唔知邊到攞個website我睇。我求其睇完就信佢繼續同佢地兩個打真軍。後來我諗番。雖然比大細佬玩得最多。但係可能佢有女友同大個啲。好多時都唔會中出我。所以我反為比細細佬中出得最多。如果有咗我估好可能係佢嘅。

直到有次我地全家去新加坡玩，我地三個同大細佬女友一間房，我估本來係想我地睇住大細佬唔好比佢同女友搞，點知就大大出乎意料之外。

https://babawk.com/thread-2195704-1-1.html:0[原文]

